---
- name: Install updates on domain controller
  hosts: all
  tasks:
    - name: search and install updates
      win_updates:
        category_names:  '*'
        reboot: yes
        reboot_timeout: 600
        log_path: c:\windows\logs\ansible_update_log.txt
      register: update_result
