---
- hosts: all
  tasks:

  - name: Single line PowerShell
 
    become: yes
    become_user: Administrator
    win_shell: |
      if(-not (Get-Module PSWindowsUpdate -ListAvailable)){
      Install-Module PSWindowsUpdate -Scope CurrentUser -Force
      }

      Get-WindowsUpdate -AcceptAll -Install -AutoReboot
